# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

check_continuous_points_above_thr <- function(v, i_start, num, thr, n_skip) {
    .Call('_MetCell_check_continuous_points_above_thr', PACKAGE = 'MetCell', v, i_start, num, thr, n_skip)
}

get_continuous_points_above_thr_idx <- function(v, i_start, num, thr, n_skip) {
    .Call('_MetCell_get_continuous_points_above_thr_idx', PACKAGE = 'MetCell', v, i_start, num, thr, n_skip)
}

find_peak_targets <- function(v, mz, mzd, scan_index, ov, num, thr = 0, n_skip = 0L) {
    .Call('_MetCell_find_peak_targets', PACKAGE = 'MetCell', v, mz, mzd, scan_index, ov, num, thr, n_skip)
}

find_greater_equal_than <- function(data, values) {
    .Call('_MetCell_find_greater_equal_than', PACKAGE = 'MetCell', data, values)
}

find_dense_min <- function(values, i_max) {
    .Call('_MetCell_find_dense_min', PACKAGE = 'MetCell', values, i_max)
}

rect_unique <- function(data, order, diff) {
    .Call('_MetCell_rect_unique', PACKAGE = 'MetCell', data, order, diff)
}

findRangeIndices <- function(x, bounds) {
    .Call('_MetCell_findRangeIndices', PACKAGE = 'MetCell', x, bounds)
}

findRangeIndicesDecreasing <- function(x, bounds) {
    .Call('_MetCell_findRangeIndicesDecreasing', PACKAGE = 'MetCell', x, bounds)
}

